# -*- mode: ruby -*-

Vagrant.configure(2) do |config|
    config.vm.box_check_update = false

    # Give VM 1/4 system memory & access to half of cpu cores on the host
    cpus = `nproc`.to_i
    cpus = [8, cpus / 2].min if cpus > 1
    mem  = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024
    mem  = mem / 4 if mem > 2048

    config.vm.define "macos" do |cfg|
        cfg.vm.provider "virtualbox" do |v|
            v.cpus   = cpus
            v.memory = mem
        end
        cfg.vm.box         = "mcandre/vagrant-macos-homebrew"
        cfg.vm.box_version = "0.0.1"
        cfg.vm.synced_folder ".", "/vagrant", disabled: true
        cfg.vm.provision     "shell", inline: %{
su vagrant -c 'brew update'
su vagrant -c 'brew install cmake rsync conan python3'
su vagrant -c 'pip3 install pyyaml'
ln -s /usr/local/bin/python3 /usr/local/bin/python
su vagrant -c 'echo "source /etc/profile">~/.bashrc'
su vagrant -c 'echo "export MACOSX_DEPLOYMENT_TARGET=10.7">>~/.bashrc'
gem install fpm --no-ri --no-rdoc
}
    end

    config.vm.define "macos_lion" do |cfg|
        cfg.vm.box         = "tuupola/osx-lion-10.7-xcode"
        cfg.vm.box_version = "10.7.5.rc1"
        cfg.vm.synced_folder ".", "/vagrant", disabled: true
        cfg.vm.provision     "shell", inline: %{
curl -fsSL -o /tmp/macports.pkg https://distfiles.macports.org/MacPorts/MacPorts-2.5.4-10.7-Lion.pkg
installer -pkg /tmp/macports.pkg -target /
/opt/local/bin/port -N install rsync py27-pip cmake
mv /opt/local/etc/rsyncd.conf.example /opt/local/etc/rsyncd.conf
/opt/local/bin/port select --set python python27
/opt/local/bin/pip-2.7 install conan
echo "/opt/local/bin">/tmp/paths
echo "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin">>/tmp/paths
echo "/opt/ruby/bin">>/tmp/paths
cat /etc/paths>>/tmp/paths
cat /tmp/paths>/etc/paths
rm /tmp/paths /tmp/macports.pkg
mkdir /tmp/ruby
/opt/local/bin/curl -fsSL https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.7.leopard_64.bottle.tar.gz | tar x --strip=2 -C /tmp/ruby
mv /tmp/ruby/ /opt
/opt/ruby/bin/gem install fpm --no-ri --no-rdoc
su vagrant -c 'echo "source /etc/profile">~/.bashrc'
}
    end

    config.vm.define "windows" do |cfg|
        cfg.vm.provider "virtualbox" do |v|
            v.cpus   = cpus
            v.memory = mem
        end
        cfg.vm.box            = "mcandre/windows-amd64"
        cfg.vm.box_version    = "0.0.1"
        cfg.vm.communicator   = :winssh
        cfg.winssh.insert_key = false

        cfg.vm.synced_folder ".", "/cygdrive/c/vagrant", disabled: true
        cfg.vm.provision     "shell", upload_path: "C:\\Windows\\Temp\\bootstrap.bat", inline: %{
choco uninstall -y rsync
cd "C:/Program Files/Git"
curl -fsSL https://downloads.sourceforge.net/msys2/rsync-3.1.3-1-x86_64.pkg.tar.xz | tar xJ
choco install -yr --no-progress python2 nsis vcbuildtools
choco install -yr --no-progress cmake --installargs 'ADD_CMAKE_TO_PATH=System'
C:/Python27/Scripts/pip install -q conan
powershell Restart-Service sshd
%}
    end

end
