ARG  from
FROM ${from}

ENV  CFLAGS=-w CXXFLAGS=-w

RUN zypper install -y \
    gzip \
    diffutils \
    fontconfig-devel \
    freetype-devel \
    gcc \
    gcc-c++ \
    libX11-devel \
    libXext-devel \
    libXrender-devel \
    libjpeg8-devel \
    libpng16-devel \
    libpng16-compat-devel \
    make \
    openssl-devel \
    perl \
    zlib-devel
