ARG  from
FROM ${from}

ARG  jpeg=libjpeg-dev
ARG  python_package=python
ARG  ssl=libssl-dev
ENV  CFLAGS=-w CXXFLAGS=-w

RUN apt-get update && apt-get install -y -q --no-install-recommends \
    build-essential \
    libfontconfig1-dev \
    libfreetype6-dev \
    $jpeg \
    libpng-dev \
    $ssl \
    libx11-dev \
    libxext-dev \
    libxrender-dev \
    $python_package \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*
